seed: 0
use_vr: true
data_path: data
save_dir: /tmp
record: true

hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - cameras: no_cameras
  - vr_input: vr_input
  - env: play_table_env
  - scene: calvin_scene_D_eval
  - robot: panda_longer_finger
  - tasks: new_playtable_tasks
  - recorder: recorder
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

exp_name: sample_8_32_n2h4_d256
prior_type : sampler # gpt or diff or sampler
use_prior: true
action_horizon: 32
num_rollout: 6
save_video: true

paths:
    stats_file_path: /satassdscratch/scml-shared/calvin_data/task_D_D/training/statistics.yaml
    model_weights_path: /satassdscratch/scml-shared/calvin_data/task_D_D/lowdim/new_endec/endec_8_0_n2h4_d256_100.bin
    prior_weights_path: /satassdscratch/scml-shared/calvin_data/task_D_D/resnet18/ckpt_diff_4_0_n2_d128_lr4_200.bin
    prior_weights_path_gpt: /satassdscratch/scml-shared/calvin_data/task_D_D/lowdim/new_prior/ckpt_gpt_4_0_n2h4_d128_lr5_100.bin
    processed_data_path: /satassdscratch/scml-shared/calvin_data/task_D_D/processed_data/resnet18_val_data_lang.npz
    sample_prior_data: /home/amete7/diffusion_dynamics/prior_sampling_data_8_32_state.npz
prior:
    vocab_size: 1004
    block_size: 5 # max skill sequence length
    output_dim: 1001
    attach_pos: [0,0]
    eos_token: 1000
    pad_token: [1001,1002]
    obs_size: 31 # 31 or 1031
    n_embd: 128
    n_head: 4
    n_layer: 2

diff_prior:
    diffusion_steps_train: 200
    diffusion_steps_eval: 200
    codebook_size: 1000
    input_dim: 10
    cond_dim: 543 # 512 (lang_clip) + 512 + 512 + 7 (front+gripper+robot_state)
    time_emb: 128
    down_dims: [128,256]
    schedule_type: ddpm # ddim or ddpm
    beta_schedule: 'squaredcos_cap_v2' # squaredcos_cap_v2 or linear
    code_length: 4

model:
     image_encoder_dim: 256
     gripper_state_dim: 7
     scene_state_dim: 24
     obs_entries: [0,2]
     act_dim: 7
     encoder_dim: 256
     skill_block_size: 32
     encoder_type: 'transformer'
     encoder_heads: 4
     encoder_layers: 2
     resid_pdrop: 0.1
     attn_pdrop: 0.1
     use_causal_attention: True
     position_embedding_type: 'rotary'
     vq_type: 'fsq'
     codebook_dim: 64
     codebook_entry: 256
     vq_decay: 0.99
     commitment_loss_weight: 0.25
     fsq_level: [8,5,5,5]
     kernel_sizes: [4,3]
     strides: [2,2]
     dilations: [1,1]
     use_residual: False # always set to false
     pooling_layers: null # [0] for avg pooling after 1st conv layer or null for no pooling
     decoder_type: 'mingpt'
     decoder_dim: 256
     gru_hidden_dim: 256
     