seed: 0
use_vr: true
data_path: data
save_dir: /tmp
record: true

hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - cameras: no_cameras
  - vr_input: vr_input
  - env: play_table_env
  - scene: calvin_scene_D_eval
  - robot: panda_longer_finger
  - tasks: new_playtable_tasks
  - recorder: recorder
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

paths:
    stats_file_path: /satassdscratch/scml-shared/calvin_data/task_D_D/training/statistics.yaml
    model_weights_path: /satassdscratch/scml-shared/calvin_data/task_D_D/ckpt_conv_1000.bin
    prior_weights_path: /satassdscratch/scml-shared/calvin_data/task_D_D/ckpt_prior_1000.bin
    processed_data_path: /satassdscratch/scml-shared/calvin_data/task_D_D/clip_data_lang.npz

prior:
    vocab_size: 1004
    block_size: 16 # max skill sequence length
    output_dim: 1001
    attach_pos: [0,1]
    eos_token: 1000
    pad_token: [1001,1002]

model:
    image_encoder_dim: 512
    gripper_state_dim: 7
    obs_entries: [1,1]
    act_dim: 7
    encoder_dim: 512
    skill_block_size: 64
    encoder_type: 'transformer'
    encoder_heads: 8
    encoder_layers: 2
    resid_pdrop: 0.1
    attn_pdrop: 0.1
    use_causal_attention: True
    position_embedding_type: 'rotary'
    vq_type: 'fsq'
    codebook_dim: 64
    codebook_entry: 512
    vq_decay: 0.99
    commitment_loss_weight: 0.25
    fsq_level: [8,5,5,5]
    kernel_sizes: [8,4]
    strides: [4,1]
    dilations: [1,2]
    decoder_type: 'mingpt'
    decoder_dim: 512
    gru_hidden_dim: 512
     